import { BasketProvider } from "@/components/BasketContext";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Create Bulberries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <BasketProvider>
            <Toaster />
            {children}
          </BasketProvider>
        </Providers>
      </body>
    </html>
  );
}
