import { DashboardNav, Navbar, SubNavbar } from "@/components";

export const metadata = {
  title: "Create Bulberries",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-h-screen min-w-screen bg-cardPrimary">
      <SubNavbar />
      <Navbar />
      <div className="container mx-auto flex flex-col gap-5">
        <DashboardNav />
        {children}
      </div>
    </div>
  );
}
