import { Text } from "@/components";
import AuthNav from "@/components/AuthNav";

export const metadata = {
  title: "Create Bulberries",
  description: "Generated by create next app",
};

interface IRootLayout {
  path: string;
  children: React.ReactNode;
}

export default function RootLayout({ children }: IRootLayout) {
  return (
    <div className="flex flex-col items-center justify-between p-10 w-screen bg-primary h-screen ">
      <div className="container flex justify-between">
        <AuthNav />
      </div>
      {children}
      <Text variant="titleSm" className="flex">
        Забыли пароль?
      </Text>
    </div>
  );
}
